[project]
name = "analyze_form"
version = "0.1.0"
description = "Structure form data using"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.120.2",
    "langchain-community>=0.4.1",
    "langchain[openai]>=1.0.3",
]
